# -*- coding: utf-8 -*-
"""CS335_PythonLab1_FizzaAli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KS1_0BARImg3f2DllZsa2klbnB_dpbL
"""

name = "Fizza Ali"
age = 23
ai_course = True
print("Name:", name)
print("Age in 5 years:", age + 5)
print("Is enrolled in CS 335 course?", ai_course)

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "RAG", "Class Probability Trees"]
for topic in topics:
 print("We will study:", topic)

student = {"name": "Fizza Ali", "score": 98}
if student["score"] >= 95:
 grade = "A+"
elif student["score"] >= 90:
 grade = "A"
elif student["score"] >= 80:
 grade = "B"
else:
 grade = "C or below"
print(f"{student['name']} received a grade of {grade}.")

def greet_student(name):
    return f"Welcome to Fizza Ali, {name}!"
# Test
print(greet_student("Fizza Ali"))

def square_num(num):
    return num ** 2
print(square_num(10))
print(square_num(15))